stages:
  - lint
  - typecheck
  - test
  - build
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

lint:
  stage: lint
  image: python:3.12
  script:
    - pip install ruff
    - ruff check event_selector tests
    - ruff format --check event_selector tests

typecheck:
  stage: typecheck
  image: python:3.12
  script:
    - pip install -e .[dev]
    - mypy event_selector

test:
  stage: test
  image: python:3.12
  script:
    - pip install -e .[dev]
    - pytest tests/ --cov=event_selector --cov-report=term --cov-report=html
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/

build:
  stage: build
  image: python:3.12
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/

release:
  stage: release
  image: python:3.12
  only:
    - tags
  script:
    - pip install twine
    - twine upload dist/*
